SHELL = /bin/sh

# edit this line to your absolute path
PROJDIR = /gig48/patrick/feret/final_release

it install depend clean bare:
	make -C src $@ PROJDIR=$(PROJDIR)

#	cd src && make $@ PROJDIR=$(PROJDIR)
